spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
           - Path= /user/**

        - id : contact-service
          uri : lb://contact/**
          predicates:
            - Path= /contact/**

server:
  port: 8999
